### ISSUE TITLE
[PE-D][Tester B] Some sections of the developer guide have placeholder text

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#363] opened 2024-11-08 23:12 UTC
Placeholder text of "_{ more test cases …​ }_" is displayed in some sections of the developer guide as seen below.

![image.png](https://raw.githubusercontent.com/Runus01/ped/main/files/6e2bbda0-b2c6-4c96-9fab-de7f5c5f1c79.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Runus01/ped#12

**Comment by seah-minlong** [comment] 2024-11-09 08:32
Duplicate of #334

**Closed by seah-minlong** 2024-11-09 08:32 UTC
