### ISSUE TITLE
[PE-D][Tester C] DG: Did not remove placeholder texts

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#352] opened 2024-11-08 22:43 UTC
Multiple instances where placeholder text in DG was not removed. 

![image.png](https://raw.githubusercontent.com/Siddardar/ped/main/files/96de30f2-87a9-4655-b0d9-0546d6efe24c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Siddardar/ped#8

**Comment by seah-minlong** [comment] 2024-11-09 08:32
Duplicate of #334

**Closed by seah-minlong** 2024-11-09 08:32 UTC
